import 'package:elomia_test/models/concern.dart';

List<Concern> concernsList = [
  Concern(
      title: 'Difficulties in relationships',
      description: 'Choose three things you want to work on first  and text'),
  Concern(title: 'Anxiety'),
  Concern(title: 'Depression'),
  Concern(
      title: 'Stress',
      description: 'Choose three things you want to work on first  and text'),
  Concern(title: 'Loneliness'),
  Concern(title: 'Low self-esteem'),
  Concern(title: 'Heartbreak'),
  Concern(title: 'Problems around eating'),
  Concern(title: 'Low mood'),
  Concern(title: 'Struggling at work'),
  Concern(title: 'Work burnout'),
  Concern(title: 'Using alcohol or other substances'),
  Concern(title: 'Self-harm'),
  Concern(title: 'Loss of a loved one'),
  Concern(title: 'Negative body image'),
  Concern(title: 'Panic attacks'),
  Concern(title: 'Mood swings'),
  Concern(title: 'Out of control feelings'),
  Concern(title: 'Worries about health'),
  Concern(title: 'Phobias'),
  Concern(title: 'Obsessional thinking'),
  Concern(title: 'Something terrible happened'),
  Concern(title: 'Flashbacks to something traumatic'),
  Concern(title: 'Inability to get to sleep or stay asleep'),
  Concern(title: 'Difficulties with sex'),
  Concern(title: 'Anxiety in social situations'),
  Concern(title: 'Low self-confidence'),
  Concern(title: 'Low motivation'),
  Concern(title: 'Negative thinking'),
  Concern(title: 'Can\'t understand myself'),
  Concern(title: 'Low focus on things'),
  Concern(title: 'Something else'),
];
